export type AcademySettings = {
  name: string;
  contact: string;
  address: string;
  logoUrl: string | null;
  mainColor: string;
  extensionAllowed: boolean;
  refundAllowed: boolean;
  makeupEnabled: boolean;
  makeupExpiresInDays: number;
  makeupMaxCount: number;
  ownerScheduleEnabled: boolean;
  ownerStudentsEnabled: boolean;
  ownerNoticesEnabled: boolean;
  teacherModeEnabled: boolean;
  studentPassEnabled: boolean;
  studentClassNotesEnabled: boolean;
  studentAbsenceRequestEnabled: boolean;
  crmEnabled: boolean;
};
